### ISSUE TITLE
Main README Basic ToDo tasks list link returns 404

### ISSUE THREAD

**Issue by magicwave** [getditto/samples#142]
On the main samples repo [README](https://github.com/getditto/samples), the [Basic ToDo tasks list](https://github.com/getditto/samples/blob/main/tasks) link returns 404. I suppose it's been renamed and moved to [template-app-electron-react-ts-todo](https://github.com/getditto/template-app-electron-react-ts-todo)?

**Comment by okdistribute** [comment]
There are many template apps now that are all in their own repositories.
