### ISSUE TITLE
Move rust template app to it's own repository

### ISSUE THREAD

**Issue by okdistribute** [getditto/samples#149]
- [ ] Make sure the example in `rs/` up to date, using best practices for the Rust SDK
- [x] Follow the pattern of other templates -- the repo should start with `template-...`
  - https://github.com/getditto/template-rust
- [ ] Link to the repo in this README
- [ ] Delete the code in this repository

**Comment by nicholastmosher** [comment]
Progress on this issue:

- [x] I've updated the Rust sample project with latest best practices and gotten it ready to publish
  - I originally made a PR on this repo but given that we'll be removing it from here, I went ahead and just moved it into it's new repository 👇 
- [x] I created https://github.com/getditto/template-rust as the new standalone repository. It's currently a private repo, but after a quick review we can make it public
- [ ] Still need to update this repo's README and delete the `rs/` code
