### ISSUE TITLE
Reorganize samples repository

### ISSUE THREAD

**Issue by okdistribute** [getditto/samples#76]
- [ ] #117
- [x] Move authentication example to it's own repository
- [x] Move CDC examples to their own repos
- [x] Delete peerslist folder, it is now in DittoSwiftTools
- [x] Remove messages example -- it is now in DemoApp-Chat-SwiftUI
- [ ] Move c-sharp-server to it's own repository
- [x] Combine the Combine work?
- [x] Organize the README of this repo to point to all of the above repositories.
- [x] #116

**Comment by magicwave** [comment]
It seems the upstream references for working branches in my local samples repo have disappeared, Tasks specifically.

**Comment by okdistribute** [comment]
Yes you'll need to reclone them I believe. Sorry about that.
